import os

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PDFstoReadFolder = os.path.join(base_dir, "QuestionstoUpload")
BackGroundImagesDir = os.path.join(base_dir, "static", "images","BackGround")
AnimeImagesDir = os.path.join(base_dir, "static", "images","AnimeArt")
#triviaquestionsfile= 
question_answer = {
    "A school has 120 students participating in a sports event. 75 of them are girls. How many are boys? Let x be the number of boys.": "45.000",
    "Each pack of erasers contains 6 pieces. Jenny bought 7 packs of erasers. How many erasers did she buy in total? Let y be the total number of erasers.": "42.000",
    "After selling 18 pens from a box containing 50 pens, how many pens are left in the box? Let z be the number of pens left.": "32.000",
    "A fruit basket has 12 apples and some oranges. There are 30 fruits in total. How many oranges are there in the basket? Let a be the number of oranges.": "18.000",
    "Each box of cookies has b pieces. 4 boxes of cookies have 48 pieces in total. How many pieces of cookies are there in each box?": "12.000",
    "A shop sold 15 shirts on Monday and 12 shirts on Tuesday. How many shirts were sold in total over the two days? Let c be the total number of shirts sold.": "27.000",
    "Daniel has d marbles. After giving away 7 marbles to his friend, he has 23 marbles left. How many marbles did Daniel have initially?": "30",
    "A bookstore has 40 fiction books and 30 non-fiction books. How many books are there in total? Let e be the total number of books.": "70.000",
    "Each pack of stickers has f pieces. Mary bought 3 packs of stickers and received 21 stickers in total. How many stickers are there in each pack?": "7.000",
    " A bakery sold 50 cupcakes in the morning and some more in the afternoon. In total, they sold 90 cupcakes that day. How many cupcakes did they sell in the afternoon? Let g be the number of cupcakes sold in the afternoon.": "40.000",
    " There are 28 red balls and h blue balls in a bag. There are 40 balls in total. How many blue balls are there in the bag?": "12.000",
    " A florist has 60 flowers in total, consisting of roses and tulips. If there are 25 roses, how many tulips are there? Let i be the number of tulips.": "35.000",
    " A bag contains 8 green candies and some yellow candies. After eating 2 yellow candies, there are 14 candies left in the bag. How many yellow candies were there initially? Let j be the initial number of yellow candies.": "8.000",
    " k plus 15 equals 40. What is the value of k?": "25.000",
    " A box of 50 donuts was divided equally among 5 friends. How many donuts did each friend receive? Let m be the number of donuts each friend received.": "10.000",
    " In a class of 30 students, there are 18 girls. How many boys are there in the class? Let n be the number of boys.": "12.000",
    " A store has p toys. After selling 12 toys, there are 28 toys left. How many toys did the store have originally?": "40.000",
    " Jane has 72 stickers. She gives away one-third of them to her sister. How many stickers does Jane have left? Let q be the number of stickers Jane has left.": "48.000",
    " r divided by 6 equals 8. What is the value of r?": "48.000",
    " A garden has 15 apple trees and some orange trees. There are 40 trees in total. How many orange trees are there in the garden? Let s be the number of orange trees.": "25.000",
    " Tom has $50. He spends $18 on a book. How much money does he have left? Let t be the amount of money Tom has left.": "32.000",
    " A school has u students. After 25 new students joined, there are now 175 students in the school. How many students were there initially?": "150.000",
    " A car travels at a constant speed of 60 km/h. How far will it travel in 3 hours? Let v be the distance traveled.": "180.000",
    " w multiplied by 5 equals 45. What is the value of w?": "9.000",
    " A restaurant has x tables. Each table can seat 4 people. If the restaurant can seat 64 people in total, how many tables are there in the restaurant?": "16.000",
    " In a library, there are 120 books on the first shelf and 90 books on the second shelf. How many books are there in total on the two shelves? Let y be the total number of books.": "210.000",
    " After using 14 sheets of paper from a stack of 50 sheets, how many sheets of paper are left in the stack? Let z be the number of sheets left.": "36.000",
    " A shop sold 28 shirts on Wednesday and some more on Thursday. In total, they sold 50 shirts over the two days. How many shirts did they sell on Thursday? Let a be the number of shirts sold on Thursday.": "22.000",
    " Each pack of pens contains b pieces. Sarah bought 6 packs of pens and received 36 pens in total. How many pens are there in each pack?": "6.000",
    " A fruit seller has 80 fruits in total, consisting of bananas and oranges. If there are 35 bananas, how many oranges are there? Let c be the number of oranges.": "45.000",
    " A cuboid box is 8 cm long, 6 cm wide and 5 cm high. What is its volume?": "240.000",
    " The volume of a cubic container is 343 cm3. What is the length of each side?": "7.000",
    " A cube has a volume of 1000 m3. What is the length of each side of the cube?": "10.000",
    " The volume of a rectangular prism is 120 cm3. If its length is 6 cm and its width is 5 cm, what is its height?": "4.000",
    " The volume of a cuboid gift box is 192 cm3. Its height is 8 cm and its width is 6 cm. What is its length?": "4.000",
    " Which unit of volume should be used to measure the volume of a pencil case? (cm3 / m3)": "cm3",
    " Which unit of volume should be used to measure the volume of a shipping container? (cm3 / m3)": "m3",
    " A 3D shape is made up of 24 cubic centimeter blocks. What is its volume in cm3?": "24.000",
    " A rectangular prism is made up of 36 cubic centimeter blocks arranged in 4 layers with 9 blocks in each layer. What is its volume in cm3?": "36.000",
    " Ben pays 48 dollars for 6 shirts. Chris buys 2 shirts. How much should he pay?": "16.000",
    " A recipe needs 2 2/3 cups of flour to make 4 muffins. How many cups of flour are needed to make 6 muffins?": "4.000",
    " 5/8 kg of sugar is about 2 1/2 cups of sugar. (a) There are 2 kg of sugar. How many cups of sugar are there? (b) There are 10 cups of sugar. How many kilograms of sugar are there?": "(a) 8.000 cups (b) 2.500 kg",
    " The total weight of 4 identical pumpkins is 18 2/5 kg. What is the total weight of 7 pumpkins?": "32.200 kg",
    " Mom uses 12 3/4 m of fabric to sew 5 dresses. There are 89 m of fabric now. How many dresses can she sew?": "35.000",
    " A motorcycle travels 135 3/4 km with 6 L of petrol. How many litres of petrol does the motorcycle need to travel 203 5/8 km?": "9.000 L",
    " 12 1/3 kg of soil is needed to plant 7 pots of roses. How many kilograms of soil are needed to plant 21 pots of roses?": "37.000 kg",
    " In a bouquet, there are 18 tulips and 12 daisies. What fraction of the flowers are tulips?": "0.600",
    " There are 24 fruits in a basket. 16 of them are apples. The others are pears. What fraction of the fruits are pears?": "0.333",
    " A bag contains 40 candies. 2/5 of them are mint candies. The others are fruit candies. (a) How many mint candies are there? (b) How many times the number of mint candies is the number of fruit candies?": "(a) 16.000 mint candies (b) 1.500 times",
    " There were 20 girls in class 5B last year. The number of girls this year is decreased by 1/4 of the number of girls last year. How many girls are there in class 5B this year?": "15.000",
    " Simplify: 1/4 + 2/3 - 1/6": "0.750",
    " Simplify: 7/15 + 4/9 - 5/18": "0.767",
    " Simplify: 11/12 - 2/3 * 1/4": "0.750",
    " Simplify: (5/6 + 1/8) * 3/5": "0.617",
    " Simplify: 4 2/5 - 1 1/3 * 3/4": "3.400",
    " Dad shares 24 3/4 kg of rice equally between Sam and Tom. Tom divides his rice into bags of 1 5/8 kg each. How many bags of rice does he have?": "7.000 bags",
    " A baker has 12 2/3 L of milk. She uses 3/4 of the milk to make 8 cakes. How many litres of milk does she need to make 1 cake?": "1.188 L (or 1.188 L)",
    " There are 5 1/6 kg of walnuts and 7 1/2 kg of cashews in a container. Mom takes out 5/9 of all the nuts. How many kilograms of nuts does she take out?": "7.037 kg (or 7.037 kg)",
    " Convert 62/2 to an improper fraction.": "31.000",
    " Convert 13/4 to a mixed number.": "3.250",
    " A rectangular prism has a length of 12 cm, width of 8 cm, and height of 5 cm. What is its volume?": "480.000 cm3",
    " The side length of a cube is 9 cm. Calculate its volume.": "729.000 cm3",
    " A cuboid box measures 6 m long, 4 m wide, and 3 m high. What is the volume of the box?": "72.000 m3",
    " The volume of a cube is 343 cm3. What is the length of one side of the cube?": "7.000 cm",
    " A rectangular container has a volume of 180 m3. If its length is 10 m and width is 6 m, find its height.": "3.000 m",
    " Which unit of volume would be most appropriate for measuring the volume of a refrigerator: cm3 or m3?": "m3",
    " Would you use cm3 or m3 to measure the volume of a shoebox?": "cm3",
    " A shipping container has a volume of 2,400 m3. If its length is 20 m and width is 10 m, what is its height?": "12.000 m",
    " A rectangular fish tank has a base area of 600 cm2 and a height of 40 cm. Calculate its volume.": "24,000.000 cm3",
    " The volume of a cube is 8 times larger than the volume of another cube. If the side length of the smaller cube is 2 cm, find the side length of the larger cube.": "4.000 cm",
    " Sarah buys 5 books for $45. How much would she pay for 8 books?": "$72.000",
    " A recipe requires 2 1/4 cups of flour to make 6 muffins. How many cups of flour are needed to make 8 muffins?": "3.000 cups",
    " 4 kg of apples cost $12. How much would 6 kg of apples cost?": "$18.000",
    " A car travels 120 km on 8 liters of fuel. How far can it travel on 5 liters of fuel?": "75.000 km",
    " A factory produces 500 toys in 4 hours. How many toys can it produce in 7 hours?": "875.000 toys",
    " In a class of 30 students, 2/5 are boys. How many girls are in the class?": "18.000 girls",
    " There are 40 marbles in a jar. 3/8 of them are red, and the rest are blue. How many blue marbles are there?": "25.000 blue marbles",
    " A bakery sold 80 cakes yesterday. 5/8 of them were chocolate cakes, and the remaining were vanilla cakes. How many vanilla cakes were sold?": "30.000 vanilla cakes",
    " In a library, 3/7 of the books are fiction, and the rest are non-fiction. If there are 4,200 non-fiction books, how many fiction books are there?": "2,400.000 fiction books",
    " A farmer has 50 animals on his farm. 2/5 are cows, 1/4 are sheep, and the rest are chickens. How many chickens does the farmer have?": "17.500 chickens",
    "Simplify to fractions: 2/3 + 1/4 - 1/6": "3/4",
    "Evaluate to fractions: 7/12 - 5/18": "5/18",
    "Calculate to fractions: 3/4 ÷ 1/3": "2 1/4",
    "Simplify to fractions: 2 1/5 - 1/3 * 1/2": "2 1/30",
    "Solve to fractions: 4 2/3 ÷ 1/4 + 2/9": "18 7/9",
    "Find the value of to fractions: 1 1/2 ÷ 3/4": "2",
    "Evaluate to fractions: 5/6 * 2/3 ÷ 1/2": "1 1/9",
    "Simplify to fractions: 2 3/4 - (1/2 + 1/3) * 3/5": "2 1/4",
    "Calculate to fractions: (2/3 + 3/4) ÷ 1/2": "2 5/6",
    "Solve to fractions: 1 1/4 ÷ 5/8 + 3/4": "2 3/4",
    "Divide to fractions: 5 ÷ 1/3": "15",
    "Evaluate to fractions: 7 ÷ 5/6": "8 2/5",
    "Simplify to fractions: 2/9 ÷ 1/3": "2/3",
    "Calculate to fractions: 3/4 ÷ 5/12": "1 4/5",
    "Solve to fractions: 1 1/2 ÷ 3/4": "2",
    "Find the value of to fractions: 2 2/3 ÷ 4/9": "6",
    "Evaluate to fractions: 5 5/6 ÷ 2 1/3": "2 1/2",
    "Simplify to fractions: 3 1/5 ÷ 1 3/4": "1 5/7",
    "Calculate to fractions: 4 2/7 ÷ 1 5/14": "3",
    "Solve to fractions: 6 3/8 ÷ 2 1/4": "2 5/6",
    "A rope 6 meters long is cut into 8 equal pieces. How long is each piece?" : "0.750 meters",
    "A cake is divided equally among 12 people. If the cake weighs 2 1/4 kg, how much cake does each person get?" : "0.188 kg",
    "A restaurant has 15 liters of soup. If they serve the soup in bowls of 3/4 liter each, how many bowls of soup can they serve?" : "20 bowls",
    "A farmer has 1 1/2 tons of feed. If he distributes it equally among his 6 cows, how much feed does each cow get?" : "0.250 tons",
    "A 5 1/4 meter long ribbon is cut into pieces, each measuring 3/4 meter. How many pieces of ribbon are there?" : "7 pieces",
    "In a fruit basket, 2/5 of the fruits are apples. If there are 30 fruits in total, how many apples are there?" : "12 apples",
    "A company spends $12,600 on 12 computers. What is the cost of each computer?" : "$1,050",
    "A school has 540 students. If 3/5 of the students are girls, how many boys are there in the school?" : "216 boys",
    "In a library, 3/8 of the books are fiction. If there are 6,400 books in total, how many non-fiction books are there?" : "4,000 non-fiction books",
    "A bakery uses 15 3/4 kg of flour to make 45 cakes. How much flour is needed to make one cake?" : "0.350 kg",
    "A water tank is 3/4 full. If it contains 1,350 liters of water, what is the total capacity of the tank?" : "1,800 liters",
    "A rectangle has a length of 5 1/2 cm and an area of 16 1/2 cm². What is its width?" : "3 cm",
    "A car travels 135 km in 2 1/4 hours. What is its average speed in km per hour?" : "60 km/h",
    "A store sold 3/5 of its inventory, which was 120 items. How many items were not sold?" : "48 items",
    "A recipe requires 2 2/3 cups of milk for 4 servings. How much milk is needed for 6 servings?" : "4 cups",
    "A garden is 12 3/4 meters long and 5 1/2 meters wide. What is its perimeter?" : "36.500 meters",
    "A pie is cut into 8 equal slices. John eats 3/8 of the pie. How many slices does he eat?" : "3 slices",
    "A team scored 140 points in 5 games. What is the team's average score per game?" : "28 points",
    "A store has a sale where the price of a shirt is reduced by 1/4. If the original price was $40, what is the sale price?" : "$30",
    "A recipe calls for 3 3/4 cups of flour. If you want to make half of the recipe, how much flour do you need?" : "1.875 cups",
    "In a class of 32 students, 3/8 play the piano. How many students don't play the piano?" : "20 students",
    "A room is 16 1/2 feet long and 12 1/4 feet wide. What is the area of the room?" : "202.125 square feet",
    "A cake recipe requires 1 1/2 cups of sugar and makes 12 servings. How much sugar is needed for 8 servings?" : "1 cup",
    "A store has 120 shirts in stock. If 2/3 of the shirts are sold, how many shirts are left?" : "40 shirts",
    "A school has 450 students. If 2/5 of the students are in the choir, how many students are not in the choir?" : "270 students",
    "A garden is 10 1/2 meters long. If its width is 2/3 of its length, what is the width of the garden?" : "7 meters",
    "A recipe makes 15 cookies and requires 1 1/4 cups of chocolate chips. How many cups of chocolate chips are needed to make 30 cookies?" : "2.500 cups",
    "A store sold 3/4 of its 240 hats. How many hats were not sold?" : "60 hats",
    "A piece of wood is 6 3/4 feet long. If it is cut into 9 equal pieces, how long is each piece?" : "0.750 feet",
    "In a bouquet, 2/5 of the flowers are roses. If there are 30 flowers in total, how many are not roses?" : "18 flowers",
    "A cake is divided into 12 equal pieces. If John eats 1/3 of the cake, how many pieces does he eat?" : "4 pieces",
    "A recipe requires 2 1/2 cups of flour for 4 servings. How much flour is needed for 6 servings?" : "3.750 cups",
    "A room is 15 3/4 feet long and 12 1/2 feet wide. What is the perimeter of the room?" : "56.500 feet",
    "A store has a sale where the price of a dress is reduced by 1/5. If the original price was $75, what is the sale price?" : "$60",
    "A recipe calls for 4 1/3 cups of sugar. If you want to make 2/3 of the recipe, how much sugar do you need?" : "2.889 cups",
    "In a group of 40 people, 3/10 are children. How many adults are in the group?" : "28 adults",
    "A rectangular field is 25 1/2 meters long and 18 3/4 meters wide. What is the area of the field?" : "478.125 square meters",
    "A cake recipe requires 1 3/4 cups of milk and makes 16 servings. How much milk is needed for 12 servings?" : "1.313 cups",
    "A store has 180 pairs of shoes in stock. If 5/9 of the shoes are sold, how many pairs of shoes are left?" : "80 pairs",
    "A company has 600 employees. If 3/8 of the employees are part-time, how many employees are full-time?" : "375 employees",
    "A rectangular swimming pool is 25 3/4 meters long. If its width is 4/5 of its length, what is the width of the pool?" : "20.600 meters",
    "A recipe makes 20 muffins and requires 1 1/2 cups of blueberries. How many cups of blueberries are needed to make 30 muffins?" : "2.250 cups",
    "A store sold 5/6 of its 360 pairs of jeans. How many pairs of jeans were not sold?" : "60 pairs",
    "A ribbon is 8 1/3 feet long. If it is cut into 5 equal pieces, how long is each piece?" : "1.667 feet",
    "In a classroom, 3/7 of the students are boys. If there are 28 students in total, how many are girls?" : "16 girls",
    "A pie is divided into 10 equal slices. If Sarah eats 2/5 of the pie, how many slices does she eat?" : "4 slices",
    "A recipe requires 3 1/3 cups of oats for 6 servings. How much oats are needed for 9 servings?" : "5 cups",
    "A room is 18 1/4 feet long and 14 2/3 feet wide. What is the area of the room?" : "267.917 square feet",
    "A store has a sale where the price of a coat is reduced by 2/7. If the original price was $140, what is the sale price?" : "$100",
    "A recipe calls for 5 2/5 cups of nuts. If you want to make 3/5 of the recipe, how many cups of nuts do you need?" : "3.250 cups",
    "Find the area of a parallelogram with a base of 12 cm and a height of 7 cm." : "84 cm²",
    "Calculate the area of a parallelogram with a base of 9 m and a height of 5 m." : "45 m²",
    "The area of a parallelogram is 54 cm² and its base is 9 cm. What is the height of the parallelogram?" : "6 cm",
    "A parallelogram has an area of 88 m². If its height is 11 m, what is the corresponding base?" : "8 m",
    "A garden is in the shape of a parallelogram. Its base and corresponding height are 8 m and 6 m respectively. What is the area of the garden?" : "48 m²",
    "Sarah is making a poster in the shape of a parallelogram. If the base is 20 cm and the height is 12 cm, what is the area of the poster?" : "240 cm²",
    "A parallelogram-shaped painting has an area of 135 cm². If the corresponding height is 9 cm, calculate the base of the painting." : "15 cm",
    "In a parallelogram, the base is 4 times the height. If the area is 100 m², find the base and height of the parallelogram." : "base: 20 m, height: 5 m",
    "The area of a parallelogram is 72 cm² and its height is 8 cm. Determine the base of the parallelogram." : "9 cm",
    "A parallelogram-shaped window has a base of 14 m. If its area is 168 m², calculate the corresponding height of the window." : "12 m",
    "Find the area of a triangle with a base of 9 cm and a corresponding height of 6 cm." : "27 cm²",
    "The base of a triangular garden is 12 m and its area is 60 m². What is the corresponding height of the garden?" : "10 m",
    "Calculate the area of a triangle with a base of 14 cm and a height of 8 cm." : "56 cm²",
    "A triangular flag has a base of 5 m and a corresponding height of 3 m. What is the area of the flag?" : "7.500 m²",
    "The area of a triangular tile is 18 cm² and its height is 6 cm. Find the base of the tile." : "6 cm",
    "A triangular piece of land has an area of 225 m² and a base of 30 m. Determine the corresponding height of the land." : "15 m",
    "Find the area of a trapezium with an upper base of 6 cm, a lower base of 10 cm, and a height of 4 cm." : "32 cm²",
    "The sum of the upper base and the lower base of a trapezium is 22 m. If the height is 7 m, what is the area of the trapezium?" : "77 m²",
    "Calculate the area of a trapezium with an upper base of 9 cm, a lower base of 15 cm, and a height of 6 cm." : "72.000 cm²",
    "A trapezium-shaped window has an upper base of 4 m, a lower base of 6 m, and an area of 35 m². What is the height of the window?" : "7.000 m",
    "The area of a trapezium is 48 cm² and its height is 8 cm. If the lower base is twice the length of the upper base, find the lengths of the upper and lower bases." : "Upper base: 4.000 cm, lower base: 8.000 cm",
    "A trapezium-shaped pool has an area of 100 m², a height of 10 m, and an upper base of 6 m. Calculate the length of the lower base." : "14.000 m",
    "In a trapezium, the upper base is 5 cm shorter than the lower base. If the lower base is 13 cm and the height is 6 cm, find the area of the trapezium." : "54.000 cm²",
    "A trapezium has an area of 81 cm², an upper base of 7 cm, and a lower base of 11 cm. Determine the height of the trapezium." : "9.000 cm",
    "The area of a trapezium-shaped garden is 70 m² and the height is 5 m. If the upper base is 8 m, what is the length of the lower base?" : "12.000 m",
    "In a triangle, the base is 3 times the height. If the area is 81 cm², find the base and height of the triangle." : "Base: 18.000 cm, height: 6.000 cm",
    "A triangular sail has an area of 52 m² and a height of 8 m. Calculate the base of the sail." : "13.000 m",
    "The area of a triangular pizza slice is 30 cm². If the base is 10 cm, what is the corresponding height?" : "6.000 cm",
    "A trapezium-shaped painting has an upper base of 12 cm, a lower base of 18 cm, and a height of 10 cm. What is the area of the painting?" : "150.000 cm²",
    "In a trapezium, the lower base is 4 m longer than the upper base. If the upper base is 6 m and the area is 55 m², find the height of the trapezium." : "5.500 m",
    "Solve the equation: 4x + 7 = 23" : "x = 4.000",
    "The area of a square is 64 cm². Find the length of one side of the square." : "8.000 cm",
    "Write an equation for the following sentence: Subtract 5 from twice a number p equals 11." : "2p - 5 = 11",
    "In the equation 3y - 8 = 16, check whether y = 8 is a solution." : "y = 8 is a solution",
    "The area of a triangle is 35 cm² and its base is 10 cm. What is the corresponding height?" : "7.000 cm",
    "Solve the equation: 2(x - 3) = 14" : "x = 10.000",
    "The area of a parallelogram is 88 m². If the height is 11 m, find the corresponding base." : "8.000 m",
    "Write an equation for the following sentence: Divide a number q by 3, then add 4 equals 10." : "q/3 + 4 = 10",
    "Solve the equation: 5x - 2 = 18" : "x = 4.000",
    "The area of a trapezium is 60 cm² and its height is 6 cm. If the lower base is 3 times the length of the upper base, find the lengths of the upper and lower bases." : "Upper base: 5.000 cm, lower base: 15.000 cm",
    "Check whether x = 7 is a solution for the equation 2x + 5 = 19." : "x = 7 is a solution",
    "The base of a triangular garden is 14 m and its area is 98 m². Find the corresponding height of the garden." : "14.000 m",
    "Solve the equation: 3(2y + 1) = 21" : "y = 3.000",
    "Write an equation for the following sentence: Multiply a number z by 4, then subtract 6 equals 18." : "4z - 6 = 18",
    "The area of a rectangular field is 240 m² and its width is 12 m. Find the length of the field." : "20.000 m",
    "Solve the equation: 4(3x - 2) = 20" : "x = 2.000",
    "Check whether y = 9 is a solution for the equation 3(y + 2) = 33." : "y = 9 is a solution",
    "The area of a parallelogram-shaped window is 72 m². If the base is 12 m, what is the corresponding height?" : "6.000 m",
    "Write an equation for the following sentence: Add 3 to five times a number w equals 28." : "5w + 3 = 28",
    "The area of a trapezium-shaped pool is 150 m², its height is 10 m, and the upper base is 8 m. Find the length of the lower base." : "22.000 m",
    "Solve the equation: 2(x + 5) - 3 = 15" : "x = 4.000",
    "In a triangle, the base is 4 times the height. If the area is 100 cm², find the base and height of the triangle." : "Base: 20.000 cm, height: 5.000 cm",
    "Write an equation for the following sentence: Multiply a number a by 2, then subtract 1 equals 13." : "2a - 1 = 13",
    "Check whether z = 6 is a solution for the equation 2(3z - 1) = 34." : "z = 6 is a solution",
    "The area of a triangular sail is 64 m² and its height is 8 m. Calculate the base of the sail." : "16.000 m",
    "Solve the equation: 3(2x - 1) + 4 = 19" : "x = 3.000",
    "The area of a parallelogram is 120 cm² and its base is 15 cm. Determine the corresponding height." : "8.000 cm",
    "Write an equation for the following sentence: Divide a number b by 4, then add 2 equals 7." : "b/4 + 2 = 7",
    "A trapezium-shaped painting has an upper base of 10 cm, a lower base of 14 cm, and an area of 120 cm². Find the height of the painting." : "10.000 cm",
    "Solve the equation: 5(x - 2) + 3 = 28" : "x = 7.000",
    "Check whether y = 9 is a solution for the equation 3(y + 2) = 33." : "y = 9 is a solution",
    "Solve the equation: 3(2x - 1) + 4 = 19" : "x = 3.000"
}
  
question_answer_1 = {
    "A school has 120 students participating in a sports event. 75 of them are girls. How many are boys? Let x be the number of boys.": "45.000",
    "Each pack of erasers contains 6 pieces. Jenny bought 7 packs of erasers. How many erasers did she buy in total? Let y be the total number of erasers.": "42.000",
    "After selling 18 pens from a box containing 50 pens, how many pens are left in the box? Let z be the number of pens left.": "32.000",
    "A fruit basket has 12 apples and some oranges. There are 30 fruits in total. How many oranges are there in the basket? Let a be the number of oranges.": "18.000",
    "Each box of cookies has b pieces. 4 boxes of cookies have 48 pieces in total. How many pieces of cookies are there in each box?": "12.000",
    "A shop sold 15 shirts on Monday and 12 shirts on Tuesday. How many shirts were sold in total over the two days? Let c be the total number of shirts sold.": "27.000",
    "Daniel has d marbles. After giving away 7 marbles to his friend, he has 23 marbles left. How many marbles did Daniel have initially?": "30.000",
    "A bookstore has 40 fiction books and 30 non-fiction books. How many books are there in total? Let e be the total number of books.": "70.000",
    "Each pack of stickers has f pieces. Mary bought 3 packs of stickers and received 21 stickers in total. How many stickers are there in each pack?": "7.000",
    " A bakery sold 50 cupcakes in the morning and some more in the afternoon. In total, they sold 90 cupcakes that day. How many cupcakes did they sell in the afternoon? Let g be the number of cupcakes sold in the afternoon.": "40.000",
    " There are 28 red balls and h blue balls in a bag. There are 40 balls in total. How many blue balls are there in the bag?": "12.000",
    " A florist has 60 flowers in total, consisting of roses and tulips. If there are 25 roses, how many tulips are there? Let i be the number of tulips.": "35.000",
    " A bag contains 8 green candies and some yellow candies. After eating 2 yellow candies, there are 14 candies left in the bag. How many yellow candies were there initially? Let j be the initial number of yellow candies.": "8.000",
    " k plus 15 equals 40. What is the value of k?": "25.000",
    " A box of 50 donuts was divided equally among 5 friends. How many donuts did each friend receive? Let m be the number of donuts each friend received.": "10.000"
}

question_answer_2 = {
    " In a class of 30 students, there are 18 girls. How many boys are there in the class? Let n be the number of boys.": "12.000",
    " A store has p toys. After selling 12 toys, there are 28 toys left. How many toys did the store have originally?": "40.000",
    " Jane has 72 stickers. She gives away one-third of them to her sister. How many stickers does Jane have left? Let q be the number of stickers Jane has left.": "48.000",
    " r divided by 6 equals 8. What is the value of r?": "48.000",
    " A garden has 15 apple trees and some orange trees. There are 40 trees in total. How many orange trees are there in the garden? Let s be the number of orange trees.": "25.000",
    " Tom has $50. He spends $18 on a book. How much money does he have left? Let t be the amount of money Tom has left.": "32.000",
    " A school has u students. After 25 new students joined, there are now 175 students in the school. How many students were there initially?": "150.000",
    " A car travels at a constant speed of 60 km/h. How far will it travel in 3 hours? Let v be the distance traveled.": "180.000",
    " w multiplied by 5 equals 45. What is the value of w?": "9.000",
    " A restaurant has x tables. Each table can seat 4 people. If the restaurant can seat 64 people in total, how many tables are there in the restaurant?": "16.000",
    " In a library, there are 120 books on the first shelf and 90 books on the second shelf. How many books are there in total on the two shelves? Let y be the total number of books.": "210.000",
    " After using 14 sheets of paper from a stack of 50 sheets, how many sheets of paper are left in the stack? Let z be the number of sheets left.": "36.000",
    " A shop sold 28 shirts on Wednesday and some more on Thursday. In total, they sold 50 shirts over the two days. How many shirts did they sell on Thursday? Let a be the number of shirts sold on Thursday.": "22.000",
    " Each pack of pens contains b pieces. Sarah bought 6 packs of pens and received 36 pens in total. How many pens are there in each pack?": "6.000",
    " A fruit seller has 80 fruits in total, consisting of bananas and oranges. If there are 35 bananas, how many oranges are there? Let c be the number of oranges.": "45.000"
}

question_answer_3 = {
   " A cuboid box is 8 cm long, 6 cm wide and 5 cm high. What is its volume?": "240.000",
    " The volume of a cubic container is 343 cm3. What is the length of each side?": "7.000",
    " A cube has a volume of 1000 m3. What is the length of each side of the cube?": "10.000",
    " The volume of a rectangular prism is 120 cm3. If its length is 6 cm and its width is 5 cm, what is its height?": "4.000",
    " The volume of a cuboid gift box is 192 cm3. Its height is 8 cm and its width is 6 cm. What is its length?": "4.000",
    " Which unit of volume should be used to measure the volume of a pencil case? (cm3 / m3)": "cm3",
    " Which unit of volume should be used to measure the volume of a shipping container? (cm3 / m3)": "m3",
    " A 3D shape is made up of 24 cubic centimeter blocks. What is its volume in cm3?": "24.000",
    " A rectangular prism is made up of 36 cubic centimeter blocks arranged in 4 layers with 9 blocks in each layer. What is its volume in cm3?": "36.000",
    " Ben pays 48 dollars for 6 shirts. Chris buys 2 shirts. How much should he pay?": "16.000",
    " A recipe needs 2 2/3 cups of flour to make 4 muffins. How many cups of flour are needed to make 6 muffins?": "4.000",
    " 5/8 kg of sugar is about 2 1/2 cups of sugar. (a) There are 2 kg of sugar. How many cups of sugar are there? (b) There are 10 cups of sugar. How many kilograms of sugar are there?": "(a) 8.000 cups (b) 2.500 kg",
    " The total weight of 4 identical pumpkins is 18 2/5 kg. What is the total weight of 7 pumpkins?": "32.200 kg",
    " Mom uses 12 3/4 m of fabric to sew 5 dresses. There are 89 m of fabric now. How many dresses can she sew?": "35.000",
    " A motorcycle travels 135 3/4 km with 6 L of petrol. How many litres of petrol does the motorcycle need to travel 203 5/8 km?": "9.000 L"
}

question_answer_4 = {
    " 12 1/3 kg of soil is needed to plant 7 pots of roses. How many kilograms of soil are needed to plant 21 pots of roses?": "37.000 kg",
    " In a bouquet, there are 18 tulips and 12 daisies. What fraction of the flowers are tulips?": "0.600",
    " There are 24 fruits in a basket. 16 of them are apples. The others are pears. What fraction of the fruits are pears?": "0.333",
    " A bag contains 40 candies. 2/5 of them are mint candies. The others are fruit candies. (a) How many mint candies are there? (b) How many times the number of mint candies is the number of fruit candies?": "(a) 16.000 mint candies (b) 1.500 times",
    " There were 20 girls in class 5B last year. The number of girls this year is decreased by 1/4 of the number of girls last year. How many girls are there in class 5B this year?": "15.000",
    "Simplify to fractions: 1/4 + 2/3 - 1/6": "3/4",
    "Simplify to fractions: 7/15 + 4/9 - 5/18": "23/30",
    "Simplify to fractions: 11/12 - 2/3 * 1/4": "3/4",
    "Simplify to fractions: (5/6 + 1/8) * 3/5": "37/60",
    "Simplify to fractions: 4 2/5 - 1 1/3 * 3/4": "3 2/5",
    " Dad shares 24 3/4 kg of rice equally between Sam and Tom. Tom divides his rice into bags of 1 5/8 kg each. How many bags of rice does he have?": "7.000 bags",
    " A baker has 12 2/3 L of milk. She uses 3/4 of the milk to make 8 cakes. How many litres of milk does she need to make 1 cake?": "1.188 L (or 1.188 L)",
    " There are 5 1/6 kg of walnuts and 7 1/2 kg of cashews in a container. Mom takes out 5/9 of all the nuts. How many kilograms of nuts does she take out?": "7.037 kg",
    " Convert 62/2 to an improper fraction.": "31.000",
    " Convert 13/4 to a mixed number.": "3.250"
}

question_answer_5 = {
    " A rectangular prism has a length of 12 cm, width of 8 cm, and height of 5 cm. What is its volume?": "480.000 cm3",
    " The side length of a cube is 9 cm. Calculate its volume.": "729.000 cm3",
    " A cuboid box measures 6 m long, 4 m wide, and 3 m high. What is the volume of the box?": "72.000 m3",
    " The volume of a cube is 343 cm3. What is the length of one side of the cube?": "7.000 cm",
    " A rectangular container has a volume of 180 m3. If its length is 10 m and width is 6 m, find its height.": "3.000 m",
    " Which unit of volume would be most appropriate for measuring the volume of a refrigerator: cm3 or m3?": "m3",
    " Would you use cm3 or m3 to measure the volume of a shoebox?": "cm3",
    " A shipping container has a volume of 2,400 m3. If its length is 20 m and width is 10 m, what is its height?": "12.000 m",
    " A rectangular fish tank has a base area of 600 cm2 and a height of 40 cm. Calculate its volume.": "24,000.000 cm3",
    " The volume of a cube is 8 times larger than the volume of another cube. If the side length of the smaller cube is 2 cm, find the side length of the larger cube.": "4.000 cm",
    " Sarah buys 5 books for $45. How much would she pay for 8 books?": "$72.000",
    " A recipe requires 2 1/4 cups of flour to make 6 muffins. How many cups of flour are needed to make 8 muffins?": "3.000 cups",
    " 4 kg of apples cost $12. How much would 6 kg of apples cost?": "$18.000",
    " A car travels 120 km on 8 liters of fuel. How far can it travel on 5 liters of fuel?": "75.000 km",
    " A factory produces 500 toys in 4 hours. How many toys can it produce in 7 hours?": "875.000 toys"
}

question_answer_6 = {
    " In a class of 30 students, 2/5 are boys. How many girls are in the class?": "18.000 girls",
    " There are 40 marbles in a jar. 3/8 of them are red, and the rest are blue. How many blue marbles are there?": "25.000 blue marbles",
    " A bakery sold 80 cakes yesterday. 5/8 of them were chocolate cakes, and the remaining were vanilla cakes. How many vanilla cakes were sold?": "30.000 vanilla cakes",
    " In a library, 3/7 of the books are fiction, and the rest are non-fiction. If there are 4,200 non-fiction books, how many fiction books are there?": "2,400.000 fiction books",
    " A farmer has 50 animals on his farm. 2/5 are cows, 1/4 are sheep, and the rest are chickens. How many chickens does the farmer have?": "17.500 chickens",
    "Simplify to fractions: 2/3 + 1/4 - 1/6": "3/4",
    "Evaluate to fractions: 7/12 - 5/18": "5/18",
    "Calculate to fractions: 3/4 ÷ 1/3": "2 1/4",
    "Simplify to fractions: 2 1/5 - 1/3 * 1/2": "2 1/30",
    "Solve to fractions: 4 2/3 ÷ 1/4 + 2/9": "18 7/9",
    "Find the value of to fractions: 1 1/2 ÷ 3/4": "2",
    "Evaluate to fractions: 5/6 * 2/3 ÷ 1/2": "1 1/9",
    "Simplify to fractions: 2 3/4 - (1/2 + 1/3) * 3/5": "2 1/4",
    "Calculate to fractions: (2/3 + 3/4) ÷ 1/2": "2 5/6",
    "Solve to fractions: 1 1/4 ÷ 5/8 + 3/4": "2 3/4"
    }

question_answer_7 = {
    "Divide to fractions: 5 ÷ 1/3": "15",
    "Evaluate to fractions: 7 ÷ 5/6": "8 2/5",
    "Simplify to fractions: 2/9 ÷ 1/3": "2/3",
    "Calculate to fractions: 3/4 ÷ 5/12": "1 4/5",
    "Solve to fractions: 1 1/2 ÷ 3/4": "2",
    "Find the value of to fractions: 2 2/3 ÷ 4/9": "6",
    "Evaluate to fractions: 5 5/6 ÷ 2 1/3": "2 1/2",
    "Simplify to fractions: 3 1/5 ÷ 1 3/4": "1 5/7",
    "Calculate to fractions: 4 2/7 ÷ 1 5/14": "3",
    "Solve to fractions: 6 3/8 ÷ 2 1/4": "2 5/6",
    "A rope 6 meters long is cut into 8 equal pieces. How long is each piece?" : "0.750 meters",
    "A cake is divided equally among 12 people. If the cake weighs 2 1/4 kg, how much cake does each person get?" : "0.188 kg",
    "A restaurant has 15 liters of soup. If they serve the soup in bowls of 3/4 liter each, how many bowls of soup can they serve?" : "20 bowls",
    "A farmer has 1 1/2 tons of feed. If he distributes it equally among his 6 cows, how much feed does each cow get?" : "0.250 tons",
    "A 5 1/4 meter long ribbon is cut into pieces, each measuring 3/4 meter. How many pieces of ribbon are there?" : "7 pieces"
}

question_answer_8 = {
    "In a fruit basket, 2/5 of the fruits are apples. If there are 30 fruits in total, how many apples are there?" : "12 apples",
    "A company spends $12,600 on 12 computers. What is the cost of each computer?" : "$1,050",
    "A school has 540 students. If 3/5 of the students are girls, how many boys are there in the school?" : "216 boys",
    "In a library, 3/8 of the books are fiction. If there are 6,400 books in total, how many non-fiction books are there?" : "4,000 non-fiction books",
    "A bakery uses 15 3/4 kg of flour to make 45 cakes. How much flour is needed to make one cake?" : "0.350 kg",
    "A water tank is 3/4 full. If it contains 1,350 liters of water, what is the total capacity of the tank?" : "1,800 liters",
    "A rectangle has a length of 5 1/2 cm and an area of 16 1/2 cm². What is its width?" : "3 cm",
    "A car travels 135 km in 2 1/4 hours. What is its average speed in km per hour?" : "60 km/h",
    "A store sold 3/5 of its inventory, which was 120 items. How many items were not sold?" : "48 items",
    "A recipe requires 2 2/3 cups of milk for 4 servings. How much milk is needed for 6 servings?" : "4 cups",
    "A garden is 12 3/4 meters long and 5 1/2 meters wide. What is its perimeter?" : "36.500 meters",
    "A pie is cut into 8 equal slices. John eats 3/8 of the pie. How many slices does he eat?" : "3 slices",
    "A team scored 140 points in 5 games. What is the team's average score per game?" : "28 points",
    "A store has a sale where the price of a shirt is reduced by 1/4. If the original price was $40, what is the sale price?" : "$30",
    "A recipe calls for 3 3/4 cups of flour. If you want to make half of the recipe, how much flour do you need?" : "1.875 cups"
}

question_answer_9 = {
    "In a class of 32 students, 3/8 play the piano. How many students don't play the piano?" : "20 students",
    "A room is 16 1/2 feet long and 12 1/4 feet wide. What is the area of the room?" : "202.125 square feet",
    "A cake recipe requires 1 1/2 cups of sugar and makes 12 servings. How much sugar is needed for 8 servings?" : "1 cup",
    "A store has 120 shirts in stock. If 2/3 of the shirts are sold, how many shirts are left?" : "40 shirts",
    "A school has 450 students. If 2/5 of the students are in the choir, how many students are not in the choir?" : "270 students",
    "A garden is 10 1/2 meters long. If its width is 2/3 of its length, what is the width of the garden?" : "7 meters",
    "A recipe makes 15 cookies and requires 1 1/4 cups of chocolate chips. How many cups of chocolate chips are needed to make 30 cookies?" : "2.500 cups",
    "A store sold 3/4 of its 240 hats. How many hats were not sold?" : "60 hats",
    "A piece of wood is 6 3/4 feet long. If it is cut into 9 equal pieces, how long is each piece?" : "0.750 feet",
    "In a bouquet, 2/5 of the flowers are roses. If there are 30 flowers in total, how many are not roses?" : "18 flowers",
    "A cake is divided into 12 equal pieces. If John eats 1/3 of the cake, how many pieces does he eat?" : "4 pieces",
    "A recipe requires 2 1/2 cups of flour for 4 servings. How much flour is needed for 6 servings?" : "3.750 cups",
    "A room is 15 3/4 feet long and 12 1/2 feet wide. What is the perimeter of the room?" : "56.500 feet",
    "A store has a sale where the price of a dress is reduced by 1/5. If the original price was $75, what is the sale price?" : "$60",
    "A recipe calls for 4 1/3 cups of sugar. If you want to make 2/3 of the recipe, how much sugar do you need?" : "2.889 cups"
}

question_answer_10 = {
    "In a group of 40 people, 3/10 are children. How many adults are in the group?" : "28 adults",
    "A rectangular field is 25 1/2 meters long and 18 3/4 meters wide. What is the area of the field?" : "478.125 square meters",
    "A cake recipe requires 1 3/4 cups of milk and makes 16 servings. How much milk is needed for 12 servings?" : "1.313 cups",
    "A store has 180 pairs of shoes in stock. If 5/9 of the shoes are sold, how many pairs of shoes are left?" : "80 pairs",
    "A company has 600 employees. If 3/8 of the employees are part-time, how many employees are full-time?" : "375 employees",
    "A rectangular swimming pool is 25 3/4 meters long. If its width is 4/5 of its length, what is the width of the pool?" : "20.600 meters",
    "A recipe makes 20 muffins and requires 1 1/2 cups of blueberries. How many cups of blueberries are needed to make 30 muffins?" : "2.250 cups",
    "A store sold 5/6 of its 360 pairs of jeans. How many pairs of jeans were not sold?" : "60 pairs",
    "A ribbon is 8 1/3 feet long. If it is cut into 5 equal pieces, how long is each piece?" : "1.667 feet",
    "In a classroom, 3/7 of the students are boys. If there are 28 students in total, how many are girls?" : "16 girls",
    "A pie is divided into 10 equal slices. If Sarah eats 2/5 of the pie, how many slices does she eat?" : "4 slices",
    "A recipe requires 3 1/3 cups of oats for 6 servings. How much oats are needed for 9 servings?" : "5 cups",
    "A room is 18 1/4 feet long and 14 2/3 feet wide. What is the area of the room?" : "267.917 square feet",
    "A store has a sale where the price of a coat is reduced by 2/7. If the original price was $140, what is the sale price?" : "$100",
    "A recipe calls for 5 2/5 cups of nuts. If you want to make 3/5 of the recipe, how many cups of nuts do you need?" : "3.250 cups"
}

question_answer_11 = {
    "Find the area of a parallelogram with a base of 12 cm and a height of 7 cm." : "84 cm²",
    "Calculate the area of a parallelogram with a base of 9 m and a height of 5 m." : "45 m²",
    "The area of a parallelogram is 54 cm² and its base is 9 cm. What is the height of the parallelogram?" : "6 cm",
    "A parallelogram has an area of 88 m². If its height is 11 m, what is the corresponding base?" : "8 m",
    "A garden is in the shape of a parallelogram. Its base and corresponding height are 8 m and 6 m respectively. What is the area of the garden?" : "48 m²",
    "Sarah is making a poster in the shape of a parallelogram. If the base is 20 cm and the height is 12 cm, what is the area of the poster?" : "240 cm²",
    "A parallelogram-shaped painting has an area of 135 cm². If the corresponding height is 9 cm, calculate the base of the painting." : "15 cm",
    "In a parallelogram, the base is 4 times the height. If the area is 100 m², find the base and height of the parallelogram." : "base: 20 m, height: 5 m",
    "The area of a parallelogram is 72 cm² and its height is 8 cm. Determine the base of the parallelogram." : "9 cm",
    "A parallelogram-shaped window has a base of 14 m. If its area is 168 m², calculate the corresponding height of the window." : "12 m",
    "Find the area of a triangle with a base of 9 cm and a corresponding height of 6 cm." : "27 cm²",
    "The base of a triangular garden is 12 m and its area is 60 m². What is the corresponding height of the garden?" : "10 m",
    "Calculate the area of a triangle with a base of 14 cm and a height of 8 cm." : "56 cm²",
    "A triangular flag has a base of 5 m and a corresponding height of 3 m. What is the area of the flag?" : "7.500 m²",
    "The area of a triangular tile is 18 cm² and its height is 6 cm. Find the base of the tile." : "6 cm"
}

question_answer_12 = {
    "A triangular piece of land has an area of 225 m² and a base of 30 m. Determine the corresponding height of the land." : "15 m",
    "Find the area of a trapezium with an upper base of 6 cm, a lower base of 10 cm, and a height of 4 cm." : "32 cm²",
    "The sum of the upper base and the lower base of a trapezium is 22 m. If the height is 7 m, what is the area of the trapezium?" : "77 m²",
    "Calculate the area of a trapezium with an upper base of 9 cm, a lower base of 15 cm, and a height of 6 cm." : "72.000 cm²",
    "A trapezium-shaped window has an upper base of 4 m, a lower base of 6 m, and an area of 35 m². What is the height of the window?" : "7.000 m",
    "The area of a trapezium is 48 cm² and its height is 8 cm. If the lower base is twice the length of the upper base, find the lengths of the upper and lower bases." : "Upper base: 4.000 cm, lower base: 8.000 cm",
    "A trapezium-shaped pool has an area of 100 m², a height of 10 m, and an upper base of 6 m. Calculate the length of the lower base." : "14.000 m",
    "In a trapezium, the upper base is 5 cm shorter than the lower base. If the lower base is 13 cm and the height is 6 cm, find the area of the trapezium." : "54.000 cm²",
    "A trapezium has an area of 81 cm², an upper base of 7 cm, and a lower base of 11 cm. Determine the height of the trapezium." : "9.000 cm",
    "The area of a trapezium-shaped garden is 70 m² and the height is 5 m. If the upper base is 8 m, what is the length of the lower base?" : "12.000 m",
    "In a triangle, the base is 3 times the height. If the area is 81 cm², find the base and height of the triangle." : "Base: 18.000 cm, height: 6.000 cm",
    "A triangular sail has an area of 52 m² and a height of 8 m. Calculate the base of the sail." : "13.000 m",
    "The area of a triangular pizza slice is 30 cm². If the base is 10 cm, what is the corresponding height?" : "6.000 cm",
    "A trapezium-shaped painting has an upper base of 12 cm, a lower base of 18 cm, and a height of 10 cm. What is the area of the painting?" : "150.000 cm²",
    "In a trapezium, the lower base is 4 m longer than the upper base. If the upper base is 6 m and the area is 55 m², find the height of the trapezium." : "5.500 m"
}

question_answer_13 = {
    "Solve the equation: 4x + 7 = 23" : "x = 4.000",
    "The area of a square is 64 cm². Find the length of one side of the square." : "8.000 cm",
    "Write an equation for the following sentence: Subtract 5 from twice a number p equals 11." : "2p - 5 = 11",
    "In the equation 3y - 8 = 16, check whether y = 8 is a solution." : "y = 8 is a solution",
    "The area of a triangle is 35 cm² and its base is 10 cm. What is the corresponding height?" : "7.000 cm",
    "Solve the equation: 2(x - 3) = 14" : "x = 10.000",
    "The area of a parallelogram is 88 m². If the height is 11 m, find the corresponding base." : "8.000 m",
    "Write an equation for the following sentence: Divide a number q by 3, then add 4 equals 10." : "q/3 + 4 = 10",
    "Solve the equation: 5x - 2 = 18" : "x = 4.000",
    "The area of a trapezium is 60 cm² and its height is 6 cm. If the lower base is 3 times the length of the upper base, find the lengths of the upper and lower bases." : "Upper base: 5.000 cm, lower base: 15.000 cm",
    "Check whether x = 7 is a solution for the equation 2x + 5 = 19." : "x = 7 is a solution",
    "The base of a triangular garden is 14 m and its area is 98 m². Find the corresponding height of the garden." : "14.000 m",
    "Solve the equation: 3(2y + 1) = 21" : "y = 3.000",
    "Write an equation for the following sentence: Multiply a number z by 4, then subtract 6 equals 18." : "4z - 6 = 18",
    "The area of a rectangular field is 240 m² and its width is 12 m. Find the length of the field." : "20.000 m"
}

question_answer_14 = {
    "Solve the equation: 4(3x - 2) = 20" : "x = 2.000",
    "Check whether y = 9 is a solution for the equation 3(y + 2) = 33." : "y = 9 is a solution",
    "The area of a parallelogram-shaped window is 72 m². If the base is 12 m, what is the corresponding height?" : "6.000 m",
    "Write an equation for the following sentence: Add 3 to five times a number w equals 28." : "5w + 3 = 28",
    "The area of a trapezium-shaped pool is 150 m², its height is 10 m, and the upper base is 8 m. Find the length of the lower base." : "22.000 m",
    "Solve the equation: 2(x + 5) - 3 = 15" : "x = 4.000",
    "In a triangle, the base is 4 times the height. If the area is 100 cm², find the base and height of the triangle." : "Base: 20.000 cm, height: 5.000 cm",
    "Write an equation for the following sentence: Multiply a number a by 2, then subtract 1 equals 13." : "2a - 1 = 13",
    "Check whether z = 6 is a solution for the equation 2(3z - 1) = 34." : "z = 6 is a solution",
    "The area of a triangular sail is 64 m² and its height is 8 m. Calculate the base of the sail." : "16.000 m",
    "Solve the equation: 3(2x - 1) + 4 = 19" : "x = 3.000",
    "The area of a parallelogram is 120 cm² and its base is 15 cm. Determine the corresponding height." : "8.000 cm",
    "Write an equation for the following sentence: Divide a number b by 4, then add 2 equals 7." : "b/4 + 2 = 7",
    "A trapezium-shaped painting has an upper base of 10 cm, a lower base of 14 cm, and an area of 120 cm². Find the height of the painting." : "10.000 cm",
    "Solve the equation: 5(x - 2) + 3 = 28" : "x = 7.000"
}

question_answer_15 = {
    "Check whether y = 9 is a solution for the equation 3(y + 2) = 33." : "y = 9 is a solution",
    "Solve the equation: 3(2x - 1) + 4 = 19" : "x = 3.000"
}