trivia_questions = {
    "1. What is the name of Blackpink's debut single?": "Whistle",
    "2. Who is the lead vocalist of the band TWICE?": "Nayeon",
    "3. What is the name of Taylor Swift's debut album?": "Taylor Swift",
    "4. Which song by Ariana Grande features the line 'I'm a lady, I'm a lady, I'm a lady'?": "God Is a Woman",
    "5. What is the name of Rihanna's debut album?": "Music of the Sun",
    "6. Who is the lead vocalist of the band Sabrina Carpenter?": "Sabrina Carpenter",
    "7. What is the name of Beyoncé's debut solo album?": "Dangerously in Love",
    "8. Which song by Meghan Trainor features the line 'I'm a lady, I'm a lady, I'm a lady'?": "All About That Bass",
    "9. What is the name of Selena Gomez's debut solo album?": "Stars Dance",
    "10. Who is the lead vocalist of the band Camila Cabello?": "Camila Cabello",
    "11. What is the name of Blackpink's debut album?": "Square One",
    "12. Who is the lead vocalist of the band TWICE?": "Jeongyeon",
    "13. What is the name of Taylor Swift's debut single?": "Tim McGraw",
    "14. Which song by Ariana Grande features the line 'I'm a lady, I'm a lady, I'm a lady'?": "God Is a Woman",
    "15. What is the name of Rihanna's debut single?": "Pon de Replay",
    "16. Who is the lead vocalist of the band Sabrina Carpenter?": "Sabrina Carpenter",
    "17. What is the name of Beyoncé's debut solo album?": "Dangerously in Love",
    "18. Which song by Meghan Trainor features the line 'I'm a lady, I'm a lady, I'm a lady'?": "All About That Bass",
    "19. What is the name of Selena Gomez's debut solo album?": "Stars Dance",
    "20. Who is the lead vocalist of the band Camila Cabello?": "Camila Cabello",
    "21. What is the name of Blackpink's debut single?": "Whistle",
    "22. Who is the lead vocalist of the band TWICE?": "Nayeon",
    "23. What is the name of Taylor Swift's debut album?": "Taylor Swift",
    "24. Which song by Ariana Grande features the line 'I'm a lady, I'm a lady, I'm a lady'?": "God Is a Woman",
    "25. What is the name of Rihanna's debut album?": "Music of the Sun",
    "26. Who is the lead vocalist of the band Sabrina Carpenter?": "Sabrina Carpenter",
    "27. What is the name of Beyoncé's debut solo album?": "Dangerously in Love",
    "28. Which song by Meghan Trainor features the line 'I'm a lady, I'm a lady, I'm a lady'?": "All About That Bass",
    "29. What is the name of Selena Gomez's debut solo album?": "Stars Dance",
    "30. Who is the lead vocalist of the band Camila Cabello?": "Camila Cabello",
    "31. What is the name of Blackpink's debut album?": "Square One",
    "32. Who is the lead vocalist of the band TWICE?": "Jeongyeon",
    "33. What is the name of Taylor Swift's debut single?": "Tim McGraw",
    "34. Which song by Ariana Grande features the line 'I'm a lady, I'm a lady, I'm a lady'?": "God Is a Woman",
    "35. What is the name of Rihanna's debut single?": "Pon de Replay",
    "36. Who is the lead vocalist of the band Sabrina Carpenter?": "Sabrina Carpenter",
    "37. What is the name of Beyoncé's debut solo album?": "Dangerously in Love",
    "38. Which song by Meghan Trainor features the line 'I'm a lady, I'm a lady, I'm a lady'?": "All About That Bass",
    "39. What is the name of Selena Gomez's debut solo album?": "Stars Dance",
    "40. Who is the lead vocalist of the band Camila Cabello?": "Camila Cabello",
    "41. What is the name of Blackpink's debut single?": "Whistle",
    "42. Who is the lead vocalist of the band TWICE?": "Nayeon",
    "43. What is the name of Taylor Swift's debut album?": "Taylor Swift",
    "44. Which song by Ariana Grande features the line 'I'm a lady, I'm a lady, I'm a lady'?": "God Is a Woman",
    "45. What is the name of Rihanna's debut album?": "Music of the Sun",
    "46. Who is the lead vocalist of the band Sabrina Carpenter?": "Sabrina Carpenter",
    "47. What is the name of Beyoncé's debut solo album?": "Dangerously in Love",
    "48. Which song by Meghan Trainor features the line 'I'm a lady, I'm a lady, I'm a lady'?": "All About That Bass",
    "49. What is the name of Selena Gomez's debut solo album?": "Stars Dance",
    "50. Who is the lead vocalist of the band Camila Cabello?": "Camila Cabello",
    "51. What is the name of Blackpink's debut album?": "Square One",
    "52. Who is the lead vocalist of the band TWICE?": "Jeongyeon",
    "53. What is the name of Taylor Swift's debut single?": "Tim McGraw",
    "54. Which song by Ariana Grande features the line 'I'm a lady, I'm a lady, I'm a lady'?": "God Is a Woman",
    "55. What is the name of Rihanna's debut single?": "Pon de Replay",
    "56. Who is the lead vocalist of the band Sabrina Carpenter?": "Sabrina Carpenter",
    "57. What is the name of Beyoncé's debut solo album?": "Dangerously in Love",
    "58. Which song by Meghan Trainor features the line 'I'm a lady, I'm a lady, I'm a lady'?": "All About That Bass",
    "59. What is the name of Selena Gomez's debut solo album?": "Stars Dance",
    "60. Who is the lead vocalist of the band Camila Cabello?": "Camila Cabello",
    "61. Who is known for the hit song 'Rolling in the Deep'?": "Adele",
    "62. Which artist released the album '1989' in 2014?": "Taylor Swift",
    "63. What is the name of the duo who created the song 'Closer' in 2016?": "The Chainsmokers",
    "64. Who sang the 2010 hit 'California Gurls' featuring Snoop Dogg?": "Katy Perry",
    "65. Which pop star is known for the song 'Bad Romance'?": "Lady Gaga",
    "66. Who is the artist behind the hit song 'Uptown Funk' featuring Bruno Mars?": "Mark Ronson",
    "67. Which singer gained fame with the song 'Poker Face'?": "Lady Gaga",
    "68. Who released the song 'Shape of You' in 2017?": "Ed Sheeran",
    "69. What is the name of the artist who sang 'Sorry' in 2015?": "Justin Bieber",
    "70. Who collaborated with Daft Punk on the song 'Get Lucky'?": "Pharrell Williams",
    "71. Which artist released the song 'Roar' in 2013?": "Katy Perry",
    "72. Who is known for the song 'Havana' featuring Young Thug?": "Camila Cabello",
    "73. Which artist sang 'All of Me' in 2013?": "John Legend",
    "74. Who released the hit song 'Someone Like You'?": "Adele",
    "75. Which pop star had a hit with 'Firework'?": "Katy Perry",
    "76. Who is the artist behind the song 'Happy'?": "Pharrell Williams",
    "77. What is the name of the singer who released 'Can't Stop the Feeling!'?": "Justin Timberlake",
    "78. Who sang 'Blank Space' in 2014?": "Taylor Swift",
    "79. Which artist is known for the hit song 'Senorita' with Shawn Mendes?": "Camila Cabello",
    "80. Who released the song 'Cheap Thrills' featuring Sean Paul?": "Sia",
    "81. Who is the singer of the song 'Counting Stars'?": "OneRepublic",
    "82. Which artist released the song 'New Rules' in 2017?": "Dua Lipa",
    "83. Who is the singer of 'Timber' featuring Kesha?": "Pitbull",
    "84. Which artist released the album 'Purpose' in 2015?": "Justin Bieber",
    "85. Who sang 'Chandelier' in 2014?": "Sia",
    "86. What is the name of the band that released 'Viva La Vida'?": "Coldplay",
    "87. Who released the song 'Royals' in 2013?": "Lorde",
    "88. Who is known for the song 'Love Yourself'?": "Justin Bieber",
    "89. Who sang 'Just the Way You Are' in 2010?": "Bruno Mars",
    "90. Which artist had a hit with 'Hotline Bling'?": "Drake",
}
